import Head from 'next/head'
import Image from 'next/image'
import { useSession, signIn, signOut } from 'next-auth/react'

export default function Home() {
  const { data: session} = useSession()
  console.log('session', session)

  if (session){
    return (
      <>
      Signed in as {session.user.email} <br/>
      <button onClick={()=> signOut()}>Sign Out</button>
      </>
    )
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    Not Signed in <br/>
    <button onClick={()=> signIn('google')}>Sign In</button>

    Welcomes
    </div>
  )
}
